version: '2.3'
services:
  allinone:
    image: ghcr.io/wy580477/leech-aio-app-ex:latest
    # 更轻量的无pyLoad版本: ghcr.io/wy580477/leech-aio-app-ex:lite
    container_name: allinone
    network_mode: host
    restart: unless-stopped
    logging:
      driver: "journald"
      # 个人偏好journald自动管理日志。
      options:
        tag: "{{.Name}}"
        # 给日志添加容器名(container_name)的tag。
    volumes:
      - ~/data:/mnt/data
      # 数据存放目录。将~/data换成你在host上想指定的目录。
    environment:
      GLOBAL_USER: admin
      # 用户名，适用于除qBittorrent外所有需要输入用户名的Web服务。
      GLOBAL_PASSWORD: password
      # 务必设置为强密码。同样适用于除qBittorrent外所有需要输入密码的Web服务，同时也是Aria2的RPC密钥。
      GLOBAL_LANGUAGE: chs
      # 设置导航页、qBittorrent和Filebrowser界面语言为中文，可选en（英文）。
      GLOBAL_PORTAL_PATH: /portal
      # 导航页路径和所有Web服务基础URL，不能为空值和"/"，后面不能加"/"。建议设置为不常见的字符串，防止字典爆破攻击。
      CADDY_DOMAIN: 
      # 举例："http://example.com" 或 "https://example.com"
      # 域名设置为有效域名（可以解析到你的host）,并且80/443端口面向公网开放，就可以启用caddy的自动申请证书开启https功能。
      # 不是一定需要付费购买域名，免费 ddns 服务域名也可以。
      # 如果在下面CADDY_EMAIL项中设置Cloudflare的DNS API申请证书，则无需占用80/443端口。
      # 设置为空值，则对外部ip开放http服务。
      CADDY_EMAIL: internal
      # 接受证书颁发机构通知邮件的地址，可以填虚假地址。
      # 可以通过Cloudflare的DNS API申请证书, 变量值需设置为"{\n dns cloudflare your_cloudflare_api_key \n}"。
      # 默认值internal为使用caddy自签证书。
      CADDY_WEB_PORT: 8080
      # 提供Web服务的端口。设置为443端口，会启动caddy自动https功能。
      OLIVETIN: Disable
      # OliveTin可以在网页上执行yt-dlp、gallery-dl和rclone等预定义shell指令，设置此项值为"Enable"开启。
      # 注意：开启后可通过OliveTin执行任意指令，不建议在安全敏感环境下使用。
      RCLONE_DAV: Enable
      # 设置值为 "Disable" 可禁用 Rclone WebDAV 服务器，可以节省约 20MB 内存。
      TZ: Asia/Shanghai
      # 指定时区。UTC为标准时间。

      # 以下环境变量为在 localhost 接口上占用的端口。除非出现端口冲突，否则保持默认值即可。
      ARIA2_PORT: 61800
      FILEBROWSER_PORT: 61801
      METUBE_PORT: 61802
      OLIVETIN_PORT: 61803
      PYLOAD_PORT: 61804
      QBT_WEBUI_PORT: 61805
      RCLONE_PORT: 61806
      RCLONE_WEBDAV_PORT: 61807
